CONFIG = {
    "USER_REQUEST": "placeholder_value",  # Replace with the actual configuration or remove if unnecessary
    "TRADE_PAIRS": ["XRPUSDT", "DOGEUSDT", "BNBUSDT", "VINEUSDT", "TSTUSDT", "AIXBTUSDT", "IPUSDT", "SUSDT", "KAIBUSDT",
                    "SUIUSDT","WIFUSDC","BBUSDT","REDUSDT","EPICUSDT","ETHUSDT",],
    "TRADE_PERCENTAGE": 0.8,
    "MAX_LEVERAGE": 1,
    "MIN_NOTIONAL": 30,
    "OBSERVATION_PERIOD": 15,
    "OBSERVATION_INTERVAL": 2,
    "OBSERVATION_EXTRA_SCORE": 5,
    "LSTM_UPDATE_THRESHOLD": 10,
    "MIN_SLOPE_THRESHOLD": 0.0001,
    "PREDICTION_WINDOW": 300,
    "PREDICTION_MULTIPLIER": 20,
    "EXPECTED_PROFIT_MULTIPLIER": 1,
    "THRESHOLD_SCORE_BUY": 60,
    "THRESHOLD_SCORE_SELL": 30,
    "MAX_PURCHASES_PER_ROUND": 10,
    "MAX_HOLD_TIME": 300,
    "MIN_MARGIN_BALANCE": 10,
    "TREND_DURATION_THRESHOLD": 1440,
    "ATR_HEDGE_THRESHOLD": 1.5
}

VERSION = "1.2.5.9.9"